---
# NFS Server Handlers
- name: restart nfs-server
  systemd:
    name: "{{ 'nfs-server' if ansible_os_family == 'RedHat' else 'nfs-kernel-server' }}"
    state: restarted

- name: reload exports
  command: exportfs -ra